

import FACTURAR.FacturarCompras;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ricardo
 */
public class ConsultarProductoCompraVenta extends javax.swing.JFrame {
public static String valor;    
DefaultTableModel model;  
    /**
     * Creates new form GestionarClientes
     */
    public ConsultarProductoCompraVenta() {
        initComponents();
        getContentPane().setBackground(Color.white);
        setResizable(false);
        setVisible(true);
        setLocation(0,0);
        setTitle("Consultar Producto");      
        setBuscar("");
         
    }
    public void setBuscar (String valor){
       String [] encabezados = {"Id","Descripción","Clave","Código"};
       String [] registros = new String[4];
       //String sql = "SELECT * FROM docente where nom_doc LIKE'%"+valor+"%'";//filtra por nombre
       //String sql = "SELECT * FROM clientes where CONCAT(idclientes,'',NombreCliente) LIKE'%"+valor+"%'";
       String sql = "SELECT * FROM inventario/productos where CONCAT(idProductos,'',DescripcionProducto,'',ClaveProducto,'',CodigoBarras) LIKE'%"+valor+"%'";
       model = new DefaultTableModel(null,encabezados);
       conectar conectar1 = new conectar();
       Connection Connection1 = conectar1.conexion();
       
        try {
        Statement st = Connection1.createStatement();
        ResultSet rs = st.executeQuery(sql);
        while (rs.next()){
            registros [0]=rs.getString("idProductos");
            registros [1]=rs.getString("DescripcionProducto");
            registros [2]=rs.getString("ClaveProducto");
            registros [3]=rs.getString("CodigoBarras");
            model.addRow(registros);
        }
        jTableVistaProductos.setModel(model);
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(null, ex);
        }
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVistaProductos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButtonproveedores = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1367, 740));
        getContentPane().setLayout(null);

        jTableVistaProductos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableVistaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableVistaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVistaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableVistaProductos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(490, 480, 640, 199);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Buscar");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(580, 240, 90, 30);

        jTextFieldBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldBuscar);
        jTextFieldBuscar.setBounds(640, 240, 390, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Proveedores 2.jpeg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, -50, 0, 790);

        jPanel1.setBackground(new java.awt.Color(241, 1, 30));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setText("Inicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonproveedores.setText("Proveedores");
        jButtonproveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonproveedoresActionPerformed(evt);
            }
        });

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo lado_1.png"))); // NOI18N
        jLabel29.setText("jLabel8");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(jButtonproveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonproveedores)
                .addContainerGap(325, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 249, 700);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo final.jpg"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(250, 0, 1070, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarKeyReleased
        // TODO add your handling code here:
        setBuscar(jTextFieldBuscar.getText());
      //  setBuscar(jTextFieldBuscar.getText());
    }//GEN-LAST:event_jTextFieldBuscarKeyReleased

    private void jTableVistaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVistaProductosMouseClicked
        if (FacturarCompras.banderaCompra == 1){ 
            DefaultTableModel model = (DefaultTableModel) jTableVistaProductos.getModel();
            valor = model.getValueAt(jTableVistaProductos.getSelectedRow(), 3).toString();
            FacturarCompras.jTextFieldCodigoBarras.setText(valor);
            FacturarCompras.jTextFieldCodigoBarras.requestFocus();
        }else if(Facturar.banderaVenta == 1){
            DefaultTableModel model = (DefaultTableModel) jTableVistaProductos.getModel();
            valor = model.getValueAt(jTableVistaProductos.getSelectedRow(), 3).toString();
            Facturar.jTextFieldCodigoBarras.setText(valor);
            Facturar.jTextFieldCodigoBarras.requestFocus();
        }
        FacturarCompra.banderaCompra = 0;
        Facturar.banderaVenta = 0;
        dispose();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableVistaProductosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Inicio in =new Inicio();
        in.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonproveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonproveedoresActionPerformed
        NuevoProveedor pv =new NuevoProveedor();
        pv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonproveedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarProductoCompraVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonproveedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVistaProductos;
    private javax.swing.JTextField jTextFieldBuscar;
    // End of variables declaration//GEN-END:variables
}
